### ISSUE TITLE
Issue with Hover

### ISSUE THREAD

**Issue by hovski** [hovski/portfolio#1]
Hey Thomas @thomasjbradley, I'm having an issue with main-card.html and was wondering if you could help.

Basically, I have it doing the white opacity on hover (with text), but it isn't filling the entire card. Do you know how I could solve this issue?

**Comment by thomasjbradley** [comment]
It needs a width & height:

```css
width: 100%;
height: 100%;
```

**Comment by hovski** [comment]
That fixed it! You're the best. Thanks again!
