### ISSUE TITLE
Card On-hover Zoom/Fade Effect

### ISSUE THREAD

**Issue by hovski** [hovski/portfolio#2]
Hey Thomas @thomasjbradley, I have 1 more question for you about (main-card.html).

I wanted to have my cards transition on hover. Basically once your mouse hovers over the card/item, the white background would appear but the text would zoom in slightly/a tiny bit slow. I've tried scaling, but I don't think I'm doing it correctly.

I assume... I would on hover do a transition: scale(1.1) (tag both the p and h3) and then over 1s reduce the scale to (1.0)?

I'm just not exactly sure how to code this without maybe keyframes? Kind of confused.

**Comment by thomasjbradley** [comment]
Yeah, scaling would work. But you cannot transition `visibility` it has no in between states. You could try switching that to `opacity` instead.

**Comment by hovski** [comment]
This one is resolved. Thanks again!
