### ISSUE TITLE
SVG Color change: Hover

### ISSUE THREAD

**Issue by hovski** [hovski/portfolio#3]
@thomasjbradley (_I swear this is the last one_). 

I followed your cheat sheet to a T. So, I'm not entirely sure why it isn't working... but the icons in my footer.html won't change colors even when I've tagged them in my css with fill, and fill on hover state.

Do you know why this is happening?

**Comment by thomasjbradley** [comment]
I think it’s because the icons don’t have a true black fill. When I look in their code the black fill colour is `#010101` it needs to be exactly `#000000` in Illustrator to allow CSS hover effects.
