### ISSUE TITLE
Pattern Library Peer Review - Sophie

### ISSUE THREAD

**Issue by ixamxkamii** [hovski/portfolio#6]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Creativeness** | Bland, boring | Fairly generic, but the colours are nice | Good, works very well and is unique enough | Wow! I never would have thought that would work so well! |
3
| **Effectiveness** | I don’t know what this is trying to do | The message isn’t completely clear and it’s difficult to use | It’s obvious and simple to use | The project is super effective and easy to use |
3
| **Quality** | Non-existent | Acceptable quality, more work could be done | Good quality, up to the expectations of the teacher | Stunning quality, this person rocks! |
3
| **Effort** | Zero effort, incomplete | Decent amount of effort | Goodly amount of effort that shows | Amazing, over-the-top amount of effort |
3
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
3
Icon-Btn only works when pulled out of the pattern library, not sure why.
Amazing work, nothing to really criticize.

**Comment by hovski** [comment]
Thanks, I'll look into these issues!
